INSERT INTO `accommodation_type` (accommodation_type_name) VALUES('Khách sạn');
INSERT INTO `accommodation_type` (accommodation_type_name) VALUES('Căn hộ');
INSERT INTO `accommodation_type` (accommodation_type_name) VALUES('Resort');
INSERT INTO `accommodation_type` (accommodation_type_name) VALUES('Biệt thự');
INSERT INTO `accommodation_type` (accommodation_type_name) VALUES('Homestay');
INSERT INTO `accommodation_type` (accommodation_type_name) VALUES('Nhà nghỉ B&B');

INSERT INTO booking_management_system.accommodation (accommodation_id, created_at, modified_at, accommodation_name, check_in, checkout, description, email, phone, star, accommodation_type_id, address_id) VALUES (1, '2024-01-03 14:46:55.272395', '2024-01-03 14:46:55.272395', 'LeaH Silk Hotel', '05:00:00', '07:00:00', 'Featuring a fitness centre, a bar as well as a garden, LeaH Silk Hotel is set in the centre of Hanoi, 300 metres from St. Joseph Cathedral. Boasting a 24-hour front desk, this property also welcomes guests with a restaurant, a water park and an outdoor pool. The accommodation offers room service and free shuttle service for guests.
At the hotel the rooms are equipped with air conditioning, a seating area, a flat-screen TV with satellite channels, a safety deposit box and a shared bathroom with a hot tub, bathrobes and slippers. All guest rooms will provide guests with a desk and a kettle.
LeaH Silk Hotel offers a terrace. Guests at the accommodation will be able to enjoy activities in and around Hanoi, like cycling.|Popular points of interest near LeaH Silk Hotel include Hoan Kiem Lake, Thang Long Water Puppet Theater and Dong Xuan Market. The nearest airport is Noi Bai International Airport, 21 km from the hotel.', 'eezele0@comcast.net', '085-069-6317', 4, 1, 1);
INSERT INTO booking_management_system.accommodation (accommodation_id, created_at, modified_at, accommodation_name, check_in, checkout, description, email, phone, star, accommodation_type_id, address_id) VALUES (2, '2024-01-07 04:24:43.893516', '2024-01-07 04:24:43.893516', 'Splendid Holiday Hotel', '05:00:00', '07:00:00', 'Chỉ cách Nhà thờ St. Joseph vài bước chân và cách Hồ Hoàn Kiếm 5 phút đi bộ, Splendid Jupiter Hotel cung cấp các phòng nghỉ cách âm với bữa sáng cũng như Wi-Fi trong phòng miễn phí ở trung tâm Hà Nội.
Các phòng yên tĩnh với cửa sổ cách âm đón chờ đón quý khách lưu trú tại khách sạn, giúp quý khách dễ dàng thư giãn với DVD hoặc truyền hình vệ tinh. Đồ uống giải khát có sẵn trong minibar. Tất cả các phòng còn có phòng tắm riêng với vòi sen sang trọng. Giỏ trái cây miễn phí được cung cấp hàng ngày cho khách.
Splendid Jupiter cung cấp dịch vụ mát-xa và phòng xông hơi khô cho những khách muốn thư giãn. Du khách cũng có thể sắp xếp đi tham quan, thuê xe hơi và xe đạp tại bàn đặt tour của khách sạn. Khách sạn cũng có dịch vụ fax và giặt thường/giặt hấp.Nhà hàng ở tầng trệt phục vụ các món ăn phương Tây và Việt Nam. Dịch vụ phòng đáp ứng yêu cầu du khách suốt 24 giờ và bữa sáng trong phòng cũng được cung cấp.
Splendid Jupiter Hotel cách Sân bay Quốc tế Nội Bài 35 km. Dịch vụ đưa/đón sân bay cũng có sẵn. Ga Hà Nội cách khách sạn 5 phút đi taxi.', 'truslinge1@chronoengine.com', '081-602-9200', 4, 1, 2);
